### ISSUE TITLE
Remove hard requirement for a model

### ISSUE THREAD

**Issue by pmackay** [trailblazer/trailblazer-generator#10]
Sometimes a cell might be needed for something that doesnt have a model, e.g. a footer. If I give a cell name of `footer` I get:

`Error: You provided an invalid class name`

Could there be a flag or some way to disable this check, and just generate the files?

**Comment by apotonick** [comment]
What about just passing a `nil` object into the cell?

**Comment by apotonick** [comment]
Ah sorry! This is the generator gem! :blush:

**Comment by emaglio** [comment]
This gem follow the [TRB file structure](http://trailblazer.to/guides/trailblazer/2.0/03-rails-basics.html#file-structure) and, at the moment, it creates files only in the `app/concepts` folder, so the name of the class is required to make sure that the file goes in the correct folder. Where do you keep your header/navigation/layout//footer files?

*BUT* maybe it make sense to add a flag to set the destination path accepting a `None` as class name for example? What do you guys think? @apotonick @fernandes

**Comment by apotonick** [comment]
Maybe we should swap the term `model` with `concept` ?

**Comment by emaglio** [comment]
Well maybe we should put both because in most of the cases it's actually a model. The error message could be something like `Error: You provided an invalid name for the model and/or the concept folder` ?

**Comment by apotonick** [comment]
We want to move away from the model-centric world view, so maybe let's drop model.

**Comment by fernandes** [comment]
yeah @pmackay the Footer doesn't need the model, but the Cell is a Ruby Class...

`trailblazer generate cell Footer`

I think you just forgot the capital F, so it's a valid Ruby name

**Comment by fernandes** [comment]
@apotonick @emaglio your are confusing ruby Class with Model/Concept hehehehe

the generator asks for a Ruby **Class** heheh

**Comment by fernandes** [comment]
ahhhh @pmackay, other thing I remembered, it doesn't need to be an existing Class on the system... just need to be a valid Ruby Class name

**Comment by pmackay** [comment]
Ah OK, thanks @fernandes! I wonder if it could work out by checking different forms, e.g. if the command line name is all lowercase, assume it needs converting _to_ a classname rather than _from_? Happy to close this though as it doesnt have a dependency on the model.

**Comment by fernandes** [comment]
ohh awesome! glad it helped you.. :)
