### ISSUE TITLE
Support Custom Templates

### ISSUE THREAD

**Issue by fernandes** [trailblazer/trailblazer-generator#4]
__Problem__

We try to do our best on supporting multiple cases on our templates, but, sometimes you wanna generate (especially views) using yours on a template.

__Solution__

The fastest solution is support custom templates, how?

1. Generator offers a command to copy default templates to a folder
2. Add the custom path to generator's cells, so it lookup

I think that check if Rails is defined, then add `Rails.root.join('lib', 'trailblazer', 'generator', 'templates', [operation,cell,view,contract], "action.e?rb")` to cell prefix can be an easy solution to this case.

Thoughts?

**Comment by emaglio** [comment]
Yeah this sounds good but I would add also the possibility to use a different view type, for example I use `slim`, something like `--view_type` as option would be good, I think

**Comment by fernandes** [comment]
great...

on rails this is:

```bash
  -e, [--template-engine=NAME]                   # Template engine to be invoked
                                                 # Default: erb
```

I think it's great to keep the same _mindset_ for our generators, I'm totally 👍 for adding a template engine support

we can organize cell templates on:

* `trailblazer/generator/builder/view/:engine/generic.erb`
* `trailblazer/generator/builder/view/erb/generic.erb`
* `trailblazer/generator/builder/view/slim/generic.erb`

for views, actually, there's only generic... 😿  no idea what we can to view templates in a generic way

**Comment by emaglio** [comment]
Done a small PR https://github.com/trailblazer/trailblazer-generator/pull/6 where I have added the `template_engine` option.
Doubt:
- should we have a control on the input allowing only `[html,haml,erb,slim..]`?

Regarding the content for the generic view I don't think we can predict much what everyone wants so I would just leave it how it is or maybe just change it to `# this is the Template for Model::Cell::Action`.

To improve the `template_engine` option we could allow to pass a file path:
`
if template_engine == existing_file
  content = file_content
  file_extension = file_extension
else
  content = generic_content
  file_extension = template_engine
end
`
make sense?

**Comment by fernandes** [comment]
> - should we have a control on the input allowing only `[html,haml,erb,slim..]`?

if we are going to support different kind of views, we must, if we are just going to put a generic one, so it's not needed... we could have `generic` for erb and slim, so we can validate just valid frameworks heheh

> To improve the `template_engine` option we could allow to pass a file path:

instead of passing a file (because if we are genering for some actions is hard to pass), my idea is the person add a templates folder on the current project, example:

I'm using trailblazer in a rails project, and add 'trailblazer-generator' to Gemfile, so on:

`Rails.root.join('lib', 'trailblazer-generator', 'templates', [operation,contract,cell], action.rb` if this file exists, we use this file, otherwise, we use our gem templates

or an idea I had right now 💡 we can pass the `--custom-templates-path`

(this default options will be great when we support a custom .yml with the configuration hahahaha)

**Comment by emaglio** [comment]
I think having a view template in the generator doesn't make much sense, just for the variety of it. Instead I would give the opportunity to use any kind of views and add a stupid content in the file that people will override, something like `here your view file`. What do you think?

 I like the idea of the `--custom-templates-path`, I think you "copy" more from other projects than the current one, anyway we can give the possibility to add multiple paths...it may take a bit longer to create the view file though.

I REALLY LIKE THE XML CONFIGURATION FILE! Maybe we should start to talk about it properly!

**Comment by fernandes** [comment]
> I think having a view template in the generator doesn't make much sense, just for the variety of it. Instead I would give the opportunity to use any kind of views and add a stupid content in the file that people will override, something like `here your view file`. What do you think?

exactly, makes sense, that's why I created a generic.erb only file... the point is, a comment is different on erb and slim, I just don't wanna break users application if we are just providing a generic file why add a `template-engine` option? I'm just thinking as a new user, so we don't confuse them

>  I like the idea of the `--custom-templates-path`, I think you "copy" more from other projects than the current one, anyway we can give the possibility to add multiple paths...it may take a bit longer to create the view file though.

sorry, didn't understand this part, but I'm totally +1 for `--custom-templates-path` option, pass 1 option and generator lookup for templates there (we add specific instructions on the README file)

> I REALLY LIKE THE XML CONFIGURATION FILE! Maybe we should start to talk about it properly!

great, I have an idea once I implemented something like this for another project, let me work on it and send some PR so we can discuss further

**Comment by marctich** [comment]
With https://github.com/trailblazer/trailblazer-generator/commit/5e196625ec1c7278c39099569c795dca87bbb349 the option is now there for when you create an entire concept.

`trailblazer g concept Post --stubs=/path/to/custom/stubs`

@emaglio we could potentially implement it for all commands.
