### ISSUE TITLE
API Generator

### ISSUE THREAD

**Issue by fernandes** [trailblazer/trailblazer-generator#5]
let's add support for API on our generator, my thoughts:

First, check this [gist](https://gist.github.com/fernandes/f379b8a6eae347eb6be1becf0677d469) about how I do API using trailblazer, @apotonick you can give some tips on best practices here.

1. `Api::V1::Thing` or `Thing` is just a matter of what name user will specify on generator, no problem
1. We *must* provide an endpoint to be used with generator templates
1. Splitting `representer` into the default, render and errors is really neat and provides great flexibility
1. Ops *must not* depend on each other (like show on create on the gist)

If we provide these operations being generated automatically, with endpoint and renders, will be awesome!

doubts:
1. should we generate inline representer or not? (actually we are generating split contracts on generator)
2. we can add --inline-representer --no-inline-representer (same for contracts) so we give flexibility
3. (personal opinion) for APIs is awesome to have contract/representer on same file, gives a great overview of the endpoint, should we keep?

**Comment by marctich** [comment]
@fernandes 
As of https://github.com/trailblazer/trailblazer-generator/commit/5e196625ec1c7278c39099569c795dca87bbb349 you can use custom stubs.

The idea is to have a few sets of stubs in a future release, which people can choose from (rails web/api, hanami web/api, etc.) as well as still giving the option for custom stubs.

You could help us with creating those ;)
